std_msgs/Header header
float32 x_axis_ctrl
float32 y_axis_ctrl
float32 z_axis_ctrl
float32 vertical_ctrl
float32 x_feed_forward
float32 y_feed_forward
uint8   flag
uint8 FLAG_TYPE_ATTI_VERT_POS = 18   # atti control
uint8 FLAG_TYPE_VELO_YAW_RATE = 72   # velocity control
uint8 FLAG_TYPE_HORIZ_ANG_VERT_VEL_YAW_ANG = 1
uint8 FLAG_VERTICAL_THRUST_HORIZONTAL_ANGLE_YAW_RATE_HORIZONTAL_BODY = 42
uint8 FLAG_VERTICAL_POSITION_HORIZONTAL_ANGLE_YAW_RATE_HORIZONTAL_BODY = 26
