geometry_msgs/Point a1_payload_position
geometry_msgs/Vector3 a2_payload_velocity
geometry_msgs/Vector3[] a3_quad_q
geometry_msgs/Vector3[] a4_quad_w
geometry_msgs/Vector3[] a5_quad_attitude
float64[] a6_quad_thrust
geometry_msgs/Vector3[] a7_quad_Omega
# internal differential states
geometry_msgs/Vector3 payload_acceleration
geometry_msgs/Vector3 payload_jerk
# internal differential states
geometry_msgs/Point[] quad_position
geometry_msgs/Vector3[] quad_velocity
geometry_msgs/Vector3[] quad_acceleration
geometry_msgs/Vector3[] quad_jerk




